safe:        false
#auto:        false
baseurl:    /

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date

husk_build_number:  3.19.4
